services:
  nginx:
    image: nginx:1.25-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"
    networks:
      - rinha

  api1:
    image: luisotte/rinha-de-backend-2026:latest
    platform: linux/amd64
    environment:
      - PORT=4000
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"
    networks:
      - rinha

  api2:
    image: luisotte/rinha-de-backend-2026:latest
    platform: linux/amd64
    environment:
      - PORT=4001
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge
