user root;
worker_processes 1;

events {
    worker_connections 4096;
    multi_accept on;
}

http {
    access_log off;
    error_log /dev/stderr warn;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_requests 100000;
    keepalive_timeout 65s;

    upstream api {
        server unix:/sockets/api1.sock;
        server unix:/sockets/api2.sock;
        keepalive 256;
    }

    server {
        listen 9999;

        location / {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_next_upstream off;
            proxy_pass http://api;
        }
    }
}
